name: Set Code Version on Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  add-commit-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set Up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Create commit info file
        run: |
          printf "Commit ID: %s\nTimestamp: %s\n" "${{ github.sha }}" "$(date +%Y-%m-%dT%H:%M:%S)" > etc/VERSION
      - name: Commit and Push File
        run: |
          git add etc/VERSION
          git commit -m "Setup Code Version"
          git push
